### ISSUE TITLE
Async Request Fail error is being encountered. 

### ISSUE THREAD

**Issue by oirtstut** [creativcoder/clinews#3]
While running the cloned project (clinews) I am encountering the following error(only in async fetch part, normal fetch working properly): 
Error: AsyncRequestFailed(reqwest::Error { kind: Decode, source: Error("missing field `articles`", line: 1, column: 156) })

**Comment by abhyuditjain** [comment]
@oirtstut I had the same issue and after a lot of debugging, I've found that you have to set the "User-Agent" header to anything. This solved the issue.

When I did not set the header, I got the following response (instead of `.json()` I did `.text()` to find why the JSON parsing was failing):

```
[newsapi/src/lib.rs:170] &response.text().await = Ok(
    "{\"status\":\"error\",\"code\":\"userAgentMissing\",\"message\":\"Please set your User-Agent header to identify your application. Anonymous requests are not allowed.\"}",
)
thread 'main' panicked at 'not yet implemented', /home/carb0n/Code/rust/news/newsapi/src/lib.rs:179:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

The complete function now is:
```
#[cfg(feature = "async")]
pub async fn fetch_async(&self) -> Result<NewsApiResponse, NewsApiError> {
    let url = self.prepare_url()?;
    let client = reqwest::Client::new();
    let response: NewsApiResponse = client
        .get(url)
        .header("Authorization", &self.api_key)
        .header("User-Agent", "NewsApiClient")
        .send()
        .await?
        .json()
        .await?;

    match response.status.as_str() {
        "ok" => Ok(response),
        _ => Err(map_response_err(response.code)),
    }
}
```

**Comment by creativcoder** [comment]
Hey thanks for reporting this. Confirm repro.

The reason it works in `fetch` (non-async) is because ureq by defaults [adds a user agent](https://github.com/algesten/ureq/blob/a367a82317a869a865c0ec9eccc362580a30ffc5/src/agent.rs#L259). Also news api might have updated their backend to require user agents.

Pushed a fix.
